this_node_address: 192.168.2.187
this_node_private_ip: 1.1.1.1
this_node_username: "admin"
this_node_password: "ChangeIt01!"
this_node_tenant_id: 

this_node_connection_string:
  server_ip: "{{ this_node_address }}"
  server_private_ip: "{{ this_node_private_ip }}"
  server_port: 5432
  user: "{{ this_node_username }}"
  password: "{{ this_node_password }}"
  auth_domain_path: "{{ this_node_tenant_id }}"
  verify: False

subscription_id: <az-subscription-id>
tenant_id: <az-tenant-id>
vault_name: ansible-cckm
resource_group_name: <az-rg-name>
az_location: eastus
secret_name: ansible-secret
connection_name: ansible