#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#
---
  - name: "Sample playbook to test CCKM Azure functionality"
    hosts: localhost
    connection: local

    vars_files:
      - vars/cckm.yml

    tasks:
    # Create Azure Connection
    - name: "Add Azure connection"
      thalesgroup.ciphertrust.connection_manager_azure:
        localNode: "{{ this_node_connection_string }}"
        op_type: create
        name: "{{ connection_name }}"
        products:
          - cckm
        client_secret: "{{ client_secret }}"
        cloud_name: AzureCloud
        client_id: "{{ client_id }}"
        tenant_id: "{{ tenant_id }}"

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    # Add vault for CCKM
    - name: "Add Azure Vault"
      thalesgroup.ciphertrust.cckm_az_vault:
        localNode: "{{ this_node_connection_string }}"
        op_type: create
        connection: "{{ connection_name }}"
        subscription_id: "{{ subscription_id }}"
        vaults:
          - name: "{{ vault_name }}"
            location: "{{ az_location }}"
            azure_vault_id: "/subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group_name }}/providers/Microsoft.KeyVault/vaults/{{ vault_name }}"
            type: "Microsoft.KeyVault/vaults"
            properties:
              tenantId: "{{ tenant_id }}"
              sku:
                family: A
                name: Standard
              vaultUri: "https://{{ vault_name }}.vault.azure.net/"
              enableSoftDelete: true
              softDeleteRetentionInDays: 7
              enableRbacAuthorization: true

    - name: "Get Vault ID from its name"
      thalesgroup.ciphertrust.cm_resource_get_id_from_name:
        localNode: "{{ this_node_connection_string }}"
        query_param: "name"
        query_param_value: "{{ vault_name }}::{{ subscription_id }}"
        resource_type: "azure-key-vault"
      register: vault

    # Create secret on vault
    - name: "Create secret on AZ KV"
      thalesgroup.ciphertrust.cckm_az_secret:
        localNode: "{{ this_node_connection_string }}"
        op_type: create
        azure_param:
          value: "{{ connection_name }}"
        key_vault: "{{ vault['response']['id'] }}"
        secret_name: "{{ secret_name }}"
      register: secret

    - name: Debug Vault Output
      debug: var=vault