#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#

---
  - name: "Create and join Ciphertrust Manager Role"
    hosts: localhost
    connection: local

    vars_files:
      - vars/cluster.yaml

    tasks:
    #Skip this task if there is already a cluster with at least one member
    - name: "Create new cluster"
      thalesgroup.ciphertrust.cm_cluster:
        localNode: "{{ this_node_connection_string }}"
        op_type: new

    - name: Pause for 1 minute to create new cluster
      ansible.builtin.pause:
        minutes: 1

    - name: "Join nodes to the cluster"
      thalesgroup.ciphertrust.cm_cluster_join:
        localNode: "{{ this_node_connection_string }}"
        op_type: join
        nodes: "{{ cluster_nodes }}"
      register: output

    - name: Pause for 2 minutes to let node join cluster
      ansible.builtin.pause:
        minutes: 2

    - name: Debug Output
      debug: var=output