#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
---
  - name: "Sample playbook for Key Management and Key Operations on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/keyMgmt.yml

    tasks:
    - name: "Create Key"
      thalesgroup.ciphertrust.vault_keys2_save:
        op_type: create
        name: "{{ key_name }}"
        algorithm: aes
        size: 256
        usageMask: 3145740
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: "Get Key ID from its name"
      thalesgroup.ciphertrust.cm_resource_get_id_from_name:
        query_param: "name"
        query_param_value: "{{ key_name }}"
        resource_type: "keys"
      register: key

    - name: "Patch Key"
      thalesgroup.ciphertrust.vault_keys2_save:
        op_type: patch
        cm_key_id: "{{ key['id'] }}"
        unexportable: false
        localNode: "{{ this_node_connection_string }}"

    - name: "Create Version"
      thalesgroup.ciphertrust.vault_keys2_save:
        op_type: create_version
        cm_key_id: "{{ key['id'] }}"
        encoding: "base64"
        localNode: "{{ this_node_connection_string }}"

    - name: Debug Output
      debug: var=output