#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#
---
  - name: "Sample playbook for Key Operations on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/keyMgmt.yml

    tasks:
    - name: "Get Key ID from its name"
      thalesgroup.ciphertrust.cm_resource_get_id_from_name:
        query_param: "name"
        query_param_value: "{{ key_name }}"
        resource_type: "keys"
      register: key

    - name: "Archive Key"
      thalesgroup.ciphertrust.vault_keys2_op:
        op_type: archive
        cm_key_id: "{{ key['id'] }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Pause until you can verify updates to an application were successful
      ansible.builtin.pause:

    - name: "Recover Key"
      thalesgroup.ciphertrust.vault_keys2_op:
        op_type: recover
        cm_key_id: "{{ key['id'] }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Pause until you can verify updates to an application were successful
      ansible.builtin.pause:

    - name: "Revoke Key"
      thalesgroup.ciphertrust.vault_keys2_op:
        op_type: revoke
        cm_key_id: "{{ key['id'] }}"
        reason: "{{ key_revocation_reason }}"
        message: "{{ key_revocation_message }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Pause until you can verify updates to an application were successful
      ansible.builtin.pause:

    - name: "Reactivate Key"
      thalesgroup.ciphertrust.vault_keys2_op:
        op_type: revoke
        cm_key_id: "{{ key['id'] }}"
        reason: "{{ key_reactivation_reason }}"
        message: "{{ key_reactivation_message }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Pause until you can verify updates to an application were successful
      ansible.builtin.pause:

    - name: "Destroy Key"
      thalesgroup.ciphertrust.vault_keys2_op:
        op_type: destroy
        cm_key_id: "{{ key['id'] }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Pause until you can verify updates to an application were successful
      ansible.builtin.pause:

    - name: "Delete Key"
      thalesgroup.ciphertrust.cm_resource_delete:
        localNode: "{{ this_node_connection_string }}"
        key: "{{ key['id'] }}"
        resource_type: "keys"

    - name: Debug Output
      debug: var=output