#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#
---
  - name: "Sample playbook for License Management on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/licenseMgmt.yml

    tasks:
    - name: "Get trial license ID from CM"
      thalesgroup.ciphertrust.license_trial_get:
        localNode: "{{ this_node_connection_string }}"
      register: license

    - name: "Activate Trial License"
      thalesgroup.ciphertrust.license_trial_action:
        action_type: activate
        trialId: "{{ license['id'] }}"
        localNode: "{{ this_node_connection_string }}"
      register: output

    - name: Paused for verifying trial license activation, press enter to continue
      ansible.builtin.pause:

    - name: "De-activate Trial License"
      thalesgroup.ciphertrust.license_trial_action:
        action_type: deactivate
        trialId: "{{ license['id'] }}"
        localNode: "{{ this_node_connection_string }}"

    # The next one requires a valid license file/information
    - name: "Add License"
      thalesgroup.ciphertrust.license_create:
        localNode: "{{ this_node_connection_string }}"
        license: "{{ license_string }}"
      ignore_errors: true # Set to true if it is ok to ignore error and continue to next step 

    - name: Debug Output
      debug: var=output