#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#
---
  - name: "Sample playbook for Group and User Management on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/userMgmt.yml

    tasks:
    - name: "Create new user"
      thalesgroup.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "create"
        username: "{{ var_username }}"
        password: "{{ var_password }}"
        email: "{{ var_email }}"
        name: "{{ var_name }}"
      register: output

    - name: "Get user ID from its name"
      thalesgroup.ciphertrust.cm_resource_get_id_from_name:
        localNode: "{{ this_node_connection_string }}"
        query_param: "username"
        query_param_value: "{{ var_username }}"
        resource_type: "users"
      register: user

    - name: "Update user info"
      thalesgroup.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "patch"
        cm_user_id: "{{ user['response']['id'] }}"
        username: "{{ var_username }}"
        email: "{{ var_new_email }}"
        name: "{{ var_new_name }}"

    - name: "Change user password"
      thalesgroup.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "changepw"
        username: "{{ var_username }}"
        password: "{{ var_password }}"
        new_password: "{{ var_new_password }}"

    - name: "Update self"
      thalesgroup.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "patch_self"
        name: "{{ var_new_self_name }}"

    - name: Debug Output
      debug: var=output