galaxy_info:
  author: Anurag Jain
  description: Developer Advocate
  company: ThalesGroup

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all

  galaxy_tags:
    - CRDP
    - ThalesGroup
    - Data Protection
    - Restful Data Protection

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
