name: Publish Collection Docs
on:
  push:
    branches:
      - main

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: thalesgroup.ciphertrust
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: thalesgroup.ciphertrust Collection
      init-copyright: thalesgroup.ciphertrust Contributors
      init-title: thalesgroup.ciphertrust Collection Documentation
      init-html-short-title: thalesgroup.ciphertrust Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://thalesgroup.github.io/CDSP-Orchestration-Ansible/branch/main/

  publish-docs-gh-pages:
    # for now we won't run this on forks
    if: github.repository == 'ThalesGroup/CDSP-Orchestration-Ansible'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
